tasks/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path("", views.ListTasksView.as_view(), name="tasks.list"),
    path("<int:page>/", views.ListTasksView.as_view(), name="tasks.list/"),
    path("insert", views.TaskInsertView.as_view(), name="tasks.insert"),
    path("update/<pk>", views.TaskUpdateView.as_view(), name="tasks.update"),
    path("delete/<pk>", views.TaskDeleteView.as_view(), name="tasks.delete"),
    path("doneTask/<task_id>", views.ListTasksView.Done_Task, name="doneTask"),
    path("category", views.CategoryInsertView.as_view(), name="tasks.category"),
]

todolist/urls.py
from django.conf import settings
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.urls import path, include


urlpatterns = [
    # path("", RedirectView.as_view(url="/tasks")),
    path("admin/", admin.site.urls),
    path("", include("homepage.urls")),
    path("tasks/", include("tasks.urls")),
    path("usuarios/", include("usuarios.urls")),
]

if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

tasks/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=264)

    def __str__(self):
        return "{} ({})".format(self.name, self.id)


class Task(models.Model):

    title = models.CharField(max_length=264)
    description = models.TextField(null=True, blank=True)
    due_to = models.DateTimeField(default=timezone.now)
    done = models.BooleanField(default=False)
    user = models.ForeignKey(
        User,
        models.SET_NULL,
        blank=True,
        null=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    def __str__(self):
        return "{} ({})".format(self.title, self.id)

    @property
    def due_to_iso(self):
        data_formatted = self.due_to.isoformat()[:10] if self.due_to else None
        return data_formatted

tasks/forms.py
from django import forms
from .models import Task, Category


class TaskModelForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            "title",
            "description",
            "due_to",
            "category",
        ]
        """
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Add some title here",
                }
            ),
            "description": forms.Textarea(attrs={"class": "form-control"}),
            "due_to": forms.TextInput(attrs={"class": "form-control"}),
        }
        """


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name"]
        """
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Add a name here",
                }
            )
        }
        """

tasks/views.py
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import reverse, render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Task, Category
from .forms import TaskModelForm, CategoryModelForm


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskModelForm
    context_object_name = "task"
    template_name = "tasks/task_update.html"
    success_message = "Task updated successfully!!!!"

    def get_success_url(self):
        messages.success(self.request, self.success_message)
        return reverse("tasks.list")


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    form_class = TaskModelForm
    context_object_name = "task"
    template_name = "tasks/task_delete.html"
    success_message = "Task deleted successfully!!!!"

    def get_success_url(self):
        messages.success(self.request, self.success_message)
        return reverse("tasks.list")


class TaskInsertView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskModelForm
    context_object_name = "task"
    template_name = "tasks/task_create.html"
    success_message = "Task created successfully!!!!"

    def catList(self):
        cat = Category.objects.all
        return cat

    def get_context_data(self, *args, **kwargs):
        context = super(TaskInsertView, self).get_context_data(*args, **kwargs)
        context['cat'] = self.catList()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super(TaskInsertView, self).form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.success_message)
        return reverse("tasks.list")


class ListTasksView(LoginRequiredMixin, ListView):
    template_name = "tasks/task_lists.html"
    model = Task
    context_object_name = "tasks"
    paginate_by = 4

    def get_context_data(self, **kwargs):
        """caso queira adicionar mais objetos no contexto"""
        context = super(ListTasksView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self, **kwargs):
        search_task = self.request.GET.get("searchTask", "")
        user_logged = self.request.user
        query = Task.objects.filter(user=user_logged)
        if search_task:
            query = query.filter(title__contains=search_task) | query.filter(
                description__contains=search_task
            )
        return query.order_by("-id").all()

    def Done_Task(request, task_id):
        item = Task.objects.get(pk=task_id)
        item.done = not item.done
        item.save()
        messages.success(request, ("Task Atualizado!"))
        return HttpResponseRedirect("/tasks/")


class CategoryInsertView(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryModelForm
    context_object_name = "category"
    template_name = "tasks/category_create.html"
    success_message = "Category created successfully!!!!"

    def get_success_url(self):
        messages.success(self.request, self.success_message)
        return reverse("tasks.insert")

tasks/templates/tasks/category_create.html
{% extends 'theme/bootstrap.html' %}

{% load widget_tweaks %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>New Category</h2>
      </div>
    </div>

    <div class="row">
        <div class="col-md-12 form-group">
            <form method='post' enctype="multipart/form-data">{% csrf_token %}
                <p>
                    <label for="id_title">Name:</label>
                    {% render_field form.name class+="form-control" placeholder=form.name.label %}
                </p>

                <div class="form-actions">
                  <button type="submit" class="btn btn-primary" >Create Category</button>
                </div>
              </form>
          </div>
      </div>

{% endblock content %}

tasks/templates/tasks/task_create.html
{% extends 'theme/bootstrap.html' %}

{% load widget_tweaks %}

{% block content %}

<!-- Message -->
{% if messages %}
{% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% endif %}
<!-- Message End -->

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>New task</h2>
      </div>
    </div>

    <!-- Add Task -->
    <div class="row">
        <div class="col-md-12 form-group">
            <form method='post' enctype="multipart/form-data">{% csrf_token %}
                <p>
                    <label for="id_title">Title:</label>
                    {% render_field form.title class+="form-control" placeholder=form.title.label %}
                </p>
                <p>
                    <label for="id_description">Description:</label>
                    {% render_field form.description class+="form-control" %}
                </p>
                <p>
                    <label for="id_due_to">Due to:</label>
                    <input type="date" name="due_to" value='{{ form.due_to.value |date:"Y-m-d" }}' class="form-control" required="" id="id_due_to" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}">
                </p>
                <p>
                    <label for="category"> Category: <a href="{% url 'tasks.category' %}" class='btn btn-sm btn-success'> + </a>
                    {% render_field form.category class+="form-control" %}
                      <!--
                      <div class="list-group">
                         for cats in cat 
                          <label class="list-group-item">
                            <input class="form-check-input me-1" type="checkbox" value="">
                             cats.name 
                          </label>
                        endfor 
                      </div>-->
                </p>
        
            <div class="form-actions">
                <button type="submit" class="btn btn-primary" >Create Task</button>
            </div>
            </form>
        </div>
    </div>

  </div>

{% endblock content %}

    

tasks/templates/tasks/task_delete.html
{% extends 'theme/bootstrap.html' %}

{% load widget_tweaks %}


{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Task #{{ task.id }}</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 form-group">
        <form method='post' enctype="multipart/form-data">{% csrf_token %}
          <p>
            <label for="id_title">Title:</label>
            <input type="text" name="title" readonly="readonly" value="{{ task.title }}" maxlength="264" class="form-control" placeholder="Title" required="" id="id_title">
          </p>
          <p>
            <label for="id_description">Description:</label>
            <textarea name="description" readonly="readonly" cols="40" rows="10" class="form-control" id="id_description">{{ task.description }}</textarea>
          </p>
          <p>
            <label for="id_due_to">Due to:</label>
            <input type="date" name="due_to" readonly="readonly" value='{{ task.due_to |date:"Y-m-d" }}' class="form-control" required="" id="id_due_to" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}">
            <input type="hidden" name="initial-due_to" value='{{ task.due_to |date:"Y-m-d" }}' id="initial-id_due_to">
          </p>

          <div class="form-actions">
            <button type="submit" class="btn btn-danger">Delete</button>
          </div>
        </form>
      </div>
    </div>

  </div>

{% endblock content %}

tasks/templates/tasks/task_lists.html
{% extends 'theme/bootstrap.html' %}

{% load humanize %}


{% block content %}

    <!-- Message -->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    <!-- Message End -->
<div class="container">

    <div class="row">
        <div class="col-sm-12">
            <h1 class="text-center">Tasks list</h1>
        </div>
    </div>

    <!-- Search Bar -->
    <form action="{% url 'tasks.list' %}" method="get" enctype="multipart/form-data" style="margin: 20px 0;">{% csrf_token %}
        <div class="row">
            <div class="col-sm-6">
                <input type="text" name="searchTask" class="form-control" placeholder="Search Task (Title/Desc)">
            </div>
            <div class="col-sm-6"> 
                <input type="submit" class="btn btn-sm btn-primary" value="Search" />
            </div>
        </div>
    </form>

    <!-- List Cards -->
            <div class="row">
                {% for task in tasks %}
                <div class="col-sm-3">

                    <div class="card card-task {% if task.done %} bg-light text-dark {% else %} bg-secondary text-white {% endif %}mb-3" id="task_{{ task.id }}">

                        <div class="card-body">

                            <h5 class="card-title">{{ task.title }}</h5>
                            <label> {{tasks.category.name}}
                            <p class="card-text">
                                <div style="width:100%;  max-width: 400px; height:100%; max-height: 60px; overflow:auto;"> 
                                {{ task.description}}  
                                </div>
                                <br>
                                {{ task.due_to|naturaltime }}
                            </p>

                            <br>
                            <a href="{% url 'tasks.update' task.id %}" class='btn btn-sm btn-info'>
                            <i class="bi bi-clipboard"></i> Update </a>
                            &nbsp;&nbsp;
                            <a href="{% url 'tasks.delete' task.id %}" class='btn btn-sm btn-danger'>
                            <i class="bi bi-trash-fill"></i> Delete </a>
                            &nbsp;&nbsp;
                             
                            {% if task.done %} <a href="{% url 'doneTask' task.id %}" class='btn btn-sm btn-secondary'>
                                <i class="bi bi-check-square-fill"></i> Undone </a>
                            {% else %}  <a href="{% url 'doneTask' task.id %}" class='btn btn-sm btn-primary'>
                                <i class="bi bi-check-square"></i>  Done </a> {% endif %}

                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        <a type="button" class="btn-danger btn-float" href="{% url 'tasks.insert' %}">
            <span class="text-size-xlarge text-bold">
            <i class="bi bi-plus"></i>
            </span>
        </a>
</div>

  
    <!-- Pagination -->
<ul class='pagination justify-content-center'>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; First</a> /
                <a href="?page={{ page_obj.previous_page_number }}">Previous</a> /
            {% else %}
                First /
                Previous /
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} / 
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">Next</a> /
                <a href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
            {% else %}
                Next /
                Last
            {% endif %}
        </span>
    </div>
  </ul>

{% endblock content %}

tasks/templates/tasks/task_update.html
{% extends 'theme/bootstrap.html' %}

{% load widget_tweaks %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>Task #{{ task.id }}</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 form-group">
        <form method='post' enctype="multipart/form-data">{% csrf_token %}
          <p>
            <label for="id_title">Title:</label>
            {% render_field form.title class+="form-control" placeholder=form.title.label %}
          </p>
          <p>
            <label for="id_description">Description:</label>
            {% render_field form.description class+="form-control" %}
          </p>
          <p>
            <label for="id_due_to">Due to:</label>
            <input type="date" name="due_to" value='{{ form.due_to.value |date:"Y-m-d" }}' class="form-control" required="" id="id_due_to" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}">
            <input type="hidden" name="initial-due_to" value='{{ form.due_to.value |date:"Y-m-d" }}' id="initial-id_due_to">            
          </p>

          <div class="form-actions">
            <button type="submit" class="btn btn-primary" >Save</button>
          </div>
        </form>
      </div>
    </div>

  </div>

{% endblock content %}